/* La Brocante de Nadine — catalogue (source unique : boutique + pages produit).
   Photos & prix d'EXEMPLE. Pièces uniques. Ajouter une pièce = un objet ici. */
window.CATALOGUE = [
  { id:"robe-fleurie", nom:"Robe fleurie", cat:"femme", catLabel:"Femme", img:"p-robe", prix:18, etat:"Très bon état", taille:"38 / M", matiere:"Coton", faitmain:false,
    desc:"Robe légère à fleurs, coupe fluide. Idéale pour l'été, avec des sandales ou des bottines." },
  { id:"manteau-laine", nom:"Manteau en laine", cat:"femme", catLabel:"Femme", img:"p-manteau", prix:24, etat:"Très bon état", taille:"40 / L", matiere:"Laine mélangée", faitmain:false,
    desc:"Manteau chaud en laine, belle tenue. Une pièce qui traverse les hivers." },
  { id:"chemisier", nom:"Chemisier", cat:"femme", catLabel:"Femme", img:"p-chemisier", prix:12, etat:"Bon état", taille:"38 / M", matiere:"Viscose", faitmain:false,
    desc:"Chemisier fluide, jolie tombée. Se glisse partout, du bureau au week-end." },
  { id:"jupe", nom:"Jupe midi", cat:"femme", catLabel:"Femme", img:"p-jupe", prix:10, etat:"Très bon état", taille:"38 / M", matiere:"Coton", faitmain:false,
    desc:"Jupe mi-longue, taille haute. Un basique qui se réinvente à chaque saison." },
  { id:"bottines-cuir", nom:"Bottines en cuir", cat:"femme", catLabel:"Femme", img:"p-bottines", prix:16, etat:"Très bon état", taille:"38", matiere:"Cuir véritable", faitmain:false,
    desc:"Bottines camel, talon bois, cuir souple avec une belle patine. Prêtes à porter." },
  { id:"sac-a-main", nom:"Sac à main", cat:"femme", catLabel:"Accessoire", img:"p-sac", prix:14, etat:"Bon état", taille:"", matiere:"Simili cuir", faitmain:false,
    desc:"Sac de tous les jours, format pratique. Chiné et vérifié." },
  { id:"pull-maille", nom:"Pull en maille", cat:"femme", catLabel:"Femme", img:"p-pull", prix:10, etat:"Bon état", taille:"M", matiere:"Laine mélangée", faitmain:false,
    desc:"Pull doux en maille, chaud et confortable. Le réflexe des jours frais." },
  { id:"chemise-homme", nom:"Chemise homme", cat:"homme", catLabel:"Homme", img:"p-chemiseH", prix:12, etat:"Très bon état", taille:"L", matiere:"Coton", faitmain:false,
    desc:"Chemise en coton, coupe classique. Un vestiaire qui dure." },
  { id:"jean-brut", nom:"Jean brut", cat:"homme", catLabel:"Homme", img:"p-jean", prix:15, etat:"Bon état", taille:"W32 / L32", matiere:"Denim", faitmain:false,
    desc:"Jean brut, coupe droite. Se patine et vieillit bien." },
  { id:"duo-vases", nom:"Duo de vases", cat:"deco", catLabel:"Déco", img:"p-vases", prix:9, etat:"Très bon état", taille:"", matiere:"Verre", faitmain:false,
    desc:"Deux vases en verre, à marier ou à séparer. Pour un bouquet ou juste pour la lumière." },
  { id:"theiere", nom:"Théière ancienne", cat:"deco", catLabel:"Déco", img:"p-theiere", prix:11, etat:"Bon état", taille:"", matiere:"Céramique", faitmain:false,
    desc:"Théière chinée, du charme d'autrefois. Pour le thé ou en objet déco." },
  { id:"horloge", nom:"Horloge ancienne", cat:"deco", catLabel:"Déco", img:"p-horloge", prix:22, etat:"Très bon état", taille:"", matiere:"Laiton", faitmain:false,
    desc:"Horloge de table ancienne, mécanisme d'époque. Une belle présence sur un buffet." },
  { id:"bougeoir", nom:"Bougeoir laiton", cat:"deco", catLabel:"Déco", img:"p-bougeoir", prix:8, etat:"Bon état", taille:"", matiere:"Laiton", faitmain:false,
    desc:"Bougeoir en laiton patiné. La petite lumière qui change une table." },
  { id:"assiettes", nom:"Assiettes anciennes", cat:"deco", catLabel:"Déco", img:"p-assiettes", prix:12, etat:"Bon état", taille:"Lot de 4", matiere:"Faïence", faitmain:false,
    desc:"Lot d'assiettes chinées, dépareillées avec goût. Pour une table qui a une âme." },
  { id:"lot-livres", nom:"Lot de livres", cat:"deco", catLabel:"Déco", img:"p-livres", prix:7, etat:"Bon état", taille:"", matiere:"Papier", faitmain:false,
    desc:"Beau lot de livres anciens, à lire ou à empiler. La déco qui raconte." },
  { id:"macrame", nom:"Suspension macramé", cat:"faitmain", catLabel:"Création · Nadine", img:"p-macrame", prix:22, etat:"Neuf — fait main", taille:"", matiere:"Coton", faitmain:true,
    desc:"Pièce faite à la main par Nadine, nouée fil à fil. Unique, forcément." },
  { id:"couronne-sechee", nom:"Couronne séchée", cat:"faitmain", catLabel:"Création · Nadine", img:"p-couronne", prix:19, etat:"Neuf — fait main", taille:"", matiere:"Fleurs séchées", faitmain:true,
    desc:"Couronne de fleurs séchées composée à la main par Nadine. Se garde longtemps." }
];
